name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: Subir a Produccion
    runs-on: ubuntu-latest
    steps:
    - name: 1. Obtener el código más reciente
      uses: actions/checkout@v4

    - name: 2. Sincronizar archivos con IONOS por SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        # Si va en la raíz déjalo así, si va en otra carpeta cámbialo a '/tu_carpeta'
        remote_path: '/' 
        sftp_only: true