name: Deploy to IONOS via FTPS

on:
  push:
    branches:
      - main # Si tu rama principal se llama 'master', cámbialo aquí.

jobs:
  web-deploy:
    name: Subir a Produccion
    runs-on: ubuntu-latest
    steps:
    - name: 1. Obtener el código más reciente
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: 2. Sincronizar archivos con IONOS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        # IMPORTANTE: Si los archivos en Ionos van dentro de una carpeta específica, 
        # colócala aquí (ej. /htdocs o /nombredeldominio.com). Si van en la raíz, déjalo en /
        server-dir: /